#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Domotica.Resource", IsApplication=true)]

namespace Domotica
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int splash_screen = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int test = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001d
			public const int abort = 2131165213;
			
			// aapt resource value: 0x7f07000a
			public const int buttonChangePinState = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int buttonConnect = 2131165193;
			
			// aapt resource value: 0x7f07001b
			public const int cknop = 2131165211;
			
			// aapt resource value: 0x7f070007
			public const int editTextIPAddress = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int editTextIPPort = 2131165192;
			
			// aapt resource value: 0x7f07001c
			public const int exit = 2131165212;
			
			// aapt resource value: 0x7f070000
			public const int relativeLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070017
			public const int relativeLayout2 = 2131165207;
			
			// aapt resource value: 0x7f070013
			public const int relativeLayout3 = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int textView1 = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int textView2 = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int textView3 = 2131165206;
			
			// aapt resource value: 0x7f070012
			public const int textView4 = 2131165202;
			
			// aapt resource value: 0x7f07000b
			public const int textViewChangePinState = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int textViewChangePinStateValue = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int textViewDebug = 2131165199;
			
			// aapt resource value: 0x7f070005
			public const int textViewIPAddress = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int textViewIPPort = 2131165190;
			
			// aapt resource value: 0x7f07000d
			public const int textViewSensor = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int textViewSensorValue = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int textViewSensorValue2 = 2131165200;
			
			// aapt resource value: 0x7f070003
			public const int textViewServer = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int textViewServerConnect = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int textViewTimerState = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int textViewTimerStateValue = 2131165186;
			
			// aapt resource value: 0x7f070018
			public const int toggleButton0 = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int toggleButton1 = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int toggleButton2 = 2131165210;
			
			// aapt resource value: 0x7f070011
			public const int toolbar1 = 2131165201;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000f
			public const int Sensor2_text = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int Sensor2_value = 2130968592;
			
			// aapt resource value: 0x7f040012
			public const int abort = 2130968594;
			
			// aapt resource value: 0x7f040000
			public const int application_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int arduino_server_connect = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int arduino_server_text = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int button_connect_text = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int button_pin_state_text = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int change_pin_state_value = 2130968588;
			
			// aapt resource value: 0x7f040011
			public const int exit = 2130968593;
			
			// aapt resource value: 0x7f040005
			public const int ip_address_text = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int ip_address_value = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int ip_port_text = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int ip_port_value = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int pin_state_text = 2130968587;
			
			// aapt resource value: 0x7f040013
			public const int schk1 = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int schk2 = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int schk3 = 2130968597;
			
			// aapt resource value: 0x7f04000d
			public const int sensor_text = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int sensor_value = 2130968590;
			
			// aapt resource value: 0x7f040001
			public const int timer_state_text = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int timer_state_value = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int MyTheme_Splash = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Theme_Custom = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
