#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Domotica.Resource", IsApplication=true)]

namespace Domotica
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fadein = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fadeout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Leftin = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Leftout = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Rightin = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Rightout = 2130968581;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int a = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int b = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int c = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int gear = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int splash_screen = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int test = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080006
			public const int btnCancel = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int btnRepeating = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int cknop = 2131230727;
			
			// aapt resource value: 0x7f08001f
			public const int exit = 2131230751;
			
			// aapt resource value: 0x7f08000b
			public const int gridLayout1 = 2131230731;
			
			// aapt resource value: 0x7f080011
			public const int gridLayout2 = 2131230737;
			
			// aapt resource value: 0x7f080014
			public const int gridLayout3 = 2131230740;
			
			// aapt resource value: 0x7f080018
			public const int gridLayout4 = 2131230744;
			
			// aapt resource value: 0x7f080017
			public const int kloktijd = 2131230743;
			
			// aapt resource value: 0x7f080004
			public const int pickTime = 2131230724;
			
			// aapt resource value: 0x7f08001c
			public const int radioButton1 = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int radioButton2 = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public const int radioButton3 = 2131230750;
			
			// aapt resource value: 0x7f08001b
			public const int radioGroup1 = 2131230747;
			
			// aapt resource value: 0x7f080012
			public const int textView1 = 2131230738;
			
			// aapt resource value: 0x7f080015
			public const int textView2 = 2131230741;
			
			// aapt resource value: 0x7f080019
			public const int textView3 = 2131230745;
			
			// aapt resource value: 0x7f080000
			public const int textView4 = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int textView5 = 2131230722;
			
			// aapt resource value: 0x7f080008
			public const int textView6 = 2131230728;
			
			// aapt resource value: 0x7f08000a
			public const int textView7 = 2131230730;
			
			// aapt resource value: 0x7f08000e
			public const int textViewDebug = 2131230734;
			
			// aapt resource value: 0x7f08000c
			public const int textViewSensor = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int textViewSensorValue = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int textViewSensorValue2 = 2131230735;
			
			// aapt resource value: 0x7f080001
			public const int textViewTimerStateValue = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int timeDisplay = 2131230723;
			
			// aapt resource value: 0x7f080013
			public const int toggleButton0 = 2131230739;
			
			// aapt resource value: 0x7f080016
			public const int toggleButton1 = 2131230742;
			
			// aapt resource value: 0x7f08001a
			public const int toggleButton2 = 2131230746;
			
			// aapt resource value: 0x7f080010
			public const int toolbar1 = 2131230736;
			
			// aapt resource value: 0x7f080009
			public const int toolbar2 = 2131230729;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int B = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int C = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int settings = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int menu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050005
			public const int Sensor2_text = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int Sensor2_value = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int abort = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int application_name = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int exit = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int schk1 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int schk2 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int schk3 = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int sensor_text = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int sensor_value = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int timer_state_text = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int timer_state_value = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int MyTheme_Splash = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int OverFlow = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int Theme_Green = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int Theme_Red = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int Theme_Yellow = 2131099651;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
